# Generated by Django 4.1.5 on 2023-01-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='temperature',
            new_name='temp',
        ),
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
