# Generated by Django 4.1.5 on 2023-01-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_alter_weather_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='pressure',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
